### ISSUE TITLE
Headings drop down list

### ISSUE THREAD

**Issue by bovisp** [getgrav/grav-plugin-editor-buttons#1]
I would love to see a heading dropdown list as well (h1-h6).

**Comment by oneleft** [comment]
This has been added as standard on grav v1.1

**Comment by rhukster** [comment]
![edit home grav 2016-05-02 17-13-45](https://cloud.githubusercontent.com/assets/1084697/14970800/41f8c9a2-1089-11e6-9711-aaae4d615907.png)

Yup! closing.
