### ISSUE TITLE
Not working on grav-admin v1.1.0-rc.4

### ISSUE THREAD

**Issue by Horadrim** [getgrav/grav-plugin-editor-buttons#10]
I have the latest version of grav-admin(v1.1.0-rc.4), but after installing the plugin, I don`t see any additional buttons:
https://i.gyazo.com/9503410e1d4f632348b17d3c3bec5bcb.png

**Comment by flaviocopes** [comment]
You have installed version `v1.1.0-beta.1` of this plugin?

**Comment by Horadrim** [comment]
Yes, I`m using the v1.1.0-beta.1

**Comment by flaviocopes** [comment]
Did you enable the editor buttons you want to have, from the plugin's configuration?

**Comment by Horadrim** [comment]
Yes, all are enabled. This is my editor-buttons.yaml:

> enabled: true
> insert_table: true
> insert_notice: true

**Comment by flaviocopes** [comment]
Mmm, strange, I cannot replicate it. 

Can you try clearing the browser cache? Also, which browser are you using?

**Comment by Horadrim** [comment]
I`m using chrome for Linux. I tried with other browsers as well - same result. I cleared both cache and cookies. I don`t even get an error, just nothing. I was hoping to use the plugin, to add some custom shortcodes to the tool bar.

**Comment by flaviocopes** [comment]
Should definitely work. Post me your user/ folder on Gitter gitter.im/flaviocopes and I'll check

**Comment by Horadrim** [comment]
Hi, I wrote to you at Gitter as you requested.

**Comment by flaviocopes** [comment]
Checked the folders sent via Gitter and I don't notice any issue on my local server, waiting for the full site to check if the problem is in there, or it's something else.

**Comment by Horadrim** [comment]
I`ve just noticed that the plugin generates some javascript errors:
https://i.gyazo.com/8a62adce5151f415040d7dd8543671f1.png

**Comment by flaviocopes** [comment]
Mmm, I cannot replicate this error. As said in Gitter, I can retry if you post the whole site so I can test with your site as you see it, rather than moving around user subfolders.

**Comment by Horadrim** [comment]
I`ve sent you the entire dir on Gitter

**Comment by flaviocopes** [comment]
Cannot replicate also with the full site, tested with Chrome. The error seems to point to a line that's valid javascript, @w00fz do you see anything strange?

**Comment by Horadrim** [comment]
Is it possible for this error to occur only in Linux (weird suggestion, I know, but still...)? I`m using Ubuntu 14.04 .

**Comment by Horadrim** [comment]
I just ran it on my Windows 10 laptop. No errors, I see the buttons. The thing is - I'm using the same plugins as on the Linux machine. I can't understand what could possibly cause this weird behavior.

**Comment by w00fz** [comment]
Doh. I used ES6 syntax and your browser might still not be supporting it entirely, perhaps on Linux because chrome on Mac seems fine.

``` js
function({ codemirror, button, textarea }) {
```

Try changing to:

``` js
function(data) {
   var codemirror = data.codemirror, button = data.button, textarea = data.textarea; 
```

Note: I haven't tested it yet

**Comment by w00fz** [comment]
Hey @Horadrim I just fixed the issue, please have a look at my commit (497037a) if you can replace the same code as in my fix and test it out, that would be great.

Thanks!

**Comment by Horadrim** [comment]
@w00fz I could test if it`s working on Monday the earliest, as the Linux I work with is on my office computer.

**Comment by w00fz** [comment]
Thanks!

**Comment by Horadrim** [comment]
@w00fz I confirm that now the plugin works on the Linux:
https://i.gyazo.com/edb62e0eb2f6f991a13367ddcfb59b43.png

Thank you, fellas! :)
