### ISSUE TITLE
Doesn't Work on Fresh Grav Install

### ISSUE THREAD

**Issue by cd13sr** [getgrav/grav-plugin-editor-buttons#13]
Hey, I just installed a fresh Grav instance (GRAV CORE + ADMIN PLUGIN), which uses the Antimatter theme. I then updated all plugins and the theme, then installed this plugin, and I'm not seeing the new buttons...

Thanks.

**Comment by flaviocopes** [comment]
Did you enable them in the plugin's configuration?

**Comment by cd13sr** [comment]
Yep, the plugin is enabled.

--------- Original Message --------- Subject: Re: [getgrav/grav-plugin-editor-buttons] Doesn't Work on Fresh Grav Install (#13)

**Comment by le717** [comment]
Grav v1.1.2, Admin v1.1.3, and Editor Buttons v1.1.1, plugin enabled and the only two options set to on. Brand new site running via XAMPP on my computer.

I am seeing the tables button in the editor and the table.css/.js load, but the notices button nor resources load. Also, looking at the code, it appears as if there are supposed to be more than two plugin options but I only have two.

**Comment by rhukster** [comment]
The notices button needs to be reworked to use the markdown notices plugin.  You will still need the markdown notices plugin installed though.. In fact we should move the button into the markdown notices plugin and out of the generic editor buttons plugin. Perhaps @flaviocopes could look at this?

**Comment by rhukster** [comment]
I think you should see some header buttons at least.

**Comment by flaviocopes** [comment]
The Notices buttons need the Markdown Notices plugin to be installed, to show up.

We can move them over to the other plugin, but then the only button left here is Insert Table, as we also moved the YouTube button to the YouTube plugin, wonder if this plugin should be the one specialized in providing the editor buttons, or just for the ones that do not belong elsewhere.
