### ISSUE TITLE
tables and unordered/ordered lists 

### ISSUE THREAD

**Issue by jbrew30** [getgrav/grav-plugin-editor-buttons#19]
When I add an unordered/ordered lists inside a table, it adds the list outside of the table. 
![In editor](https://cloud.githubusercontent.com/assets/22452733/18841714/9e16f45a-83e0-11e6-89de-b90b2295b501.png)
![Front-end](https://cloud.githubusercontent.com/assets/22452733/18841799/dc4c1c0a-83e0-11e6-8cbc-4a5619f62185.png)

**Comment by jbrew30** [comment]
I've also noticed that you can't even use line breaks. It will jump right out of the table. So you can't make tables like this:
![screen shot 2016-09-26 at 1 13 04 pm](https://cloud.githubusercontent.com/assets/22452733/18844371/01cb6058-83eb-11e6-96a5-5b5b417ff637.png)

**Comment by flaviocopes** [comment]
Markdown (or Markdown extra) do not really support this.

See http://stackoverflow.com/questions/19950648/how-to-write-lists-inside-a-markdown-table for some hints on using HTML inside markdown

**Comment by jbrew30** [comment]
Thanks for your reply! I ended up realizing that this was the only option but, was hoping it was just something I messed. Using straight HTML isn't very "client friendly" but I know this is probably a GRAV WYSIWYG issue and not your plugin. Hopefully, they will add this feature in future updates.

**Comment by flaviocopes** [comment]
The plugin is part of Grav core, it simply makes easier to add the table, but the issue is more in Markdown itself which does not permit such markup in the table directly.

When we'll add a WYSIWYG this will probably be solved differently.
