### ISSUE TITLE
Code Line and Code Block Button

### ISSUE THREAD

**Issue by msdundar** [getgrav/grav-plugin-editor-buttons#24]
Do you plan to add a button feature for adding codes to a post?

I mean this characters => ```

**Comment by flaviocopes** [comment]
Not in the plans but we accept PRs that add new buttons, e.g. https://github.com/getgrav/grav-plugin-editor-buttons/pull/23

**Comment by paulmassen** [comment]
https://github.com/getgrav/grav-plugin-editor-buttons/pull/26

**Comment by kristoferus75** [comment]
Hi ! 

It work perfectly if i mark one line !

But if i mark more lines it doesnt work correctly ! 

it looks like this :


```
```
```
   xxx   
```
```
```
xxx
xxx

**Comment by paulmassen** [comment]
fixed in fe64558
